# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFundingGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.BooleanField(choices=[(0, b'Audience'), (1, b'Player')], default=b'0'),
        ),
    ]
