# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFundingGame', '0002_remove_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[(b'A', b'Audience'), (b'P', b'Player')], max_length=1),
        ),
    ]
